# Generated by Django 3.2.15 on 2022-12-06 20:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221206_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='memes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meme_categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('animals', 'animals'), ('fail', 'fail'), ('confused', 'confused'), ('gaming', 'gaming')], max_length=28, null=True),
        ),
    ]
