version: "3.7"

x-service-volumes: &service-volumes
  - ./:/app/rw.cached

x-database-variables: &database-variables
  POSTGRES_DB: dadailymemes-data
  POSTGRES_USER: dadailymemes-user
  POSTGRES_PASSWORD: postgres

x-app-variables: &app-variables
  <<: *database-variables
  POSTGRES_HOST: 35.185.198.0

services:
  website:
    image: dadailymemes_website:latest
    command: python manage.py runserver 0.0.0.0:8000 
    volumes: *service-volumes
    depends_on:
      - db_migrate
    ports:
      - "8000:8000"
    environment: *app-variables


  db_migrate:
    image: dadailymemes_website:latest
    command: python manage.py migrate
    volumes: *service-volumes
    environment: *app-variables
    depends_on:
      - postgres


  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment: *database-variables
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
